package Just_Forge_2D.Utils;

import Just_Forge_2D.InputSystem.Keys;
import imgui.ImVec2;
import imgui.ImVec4;
import org.jbox2d.common.Vec2;
import org.joml.Vector2f;
import org.joml.Vector3f;
import org.joml.Vector4f;

public class DefaultValues
{
    public static final float GRID_WIDTH = 0.25f;
    public static final float GRID_HEIGHT = 0.25f;
    public static final int MAX_BATCH_SIZE = 1024;
    public static final int DEBUG_PENCIL_MAX_LINES = 2048;
    public static final int DEBUG_PENCIL_DEFAULT_LIFE = 1;
    public static final Vector3f DEBUG_PENCIL_DEFAULT_COLOR = new Vector3f(1, 1, 1);
    public static final int DEBUG_PENCIL_DEFAULT_WIDTH = 4;
    public static final int DEBUG_PENCIL_DEFAULT_CIRCLE_PRECISION = 16;
    public static final float DEBUG_PENCIL_DEFAULT_ROTATION = 0f;
    public static final Vec2 GRAVITY = new Vec2(0, -10f);
    public static final float PHYSICS_DELTA_TIME = 1.0f / 60f;
    public static final int VELOCITY_ITERATIONS = 8;
    public static final int POSITION_ITERATIONS = 3;
    public static final float LINEAR_DAMPING = 0.9f;
    public static final float ANGULAR_DAMPING = 0.8f;
    public static final float DEFAULT_MASS = 1f;
    public static final boolean ROTATION_FIXED = false;
    public static final boolean CONTINUOUS_COLLISION = false;
    public static final float GRAVITY_SCALE = 1.0f;
    public static final float DEFAULT_ROTATION = 0.0f;
    public static final int DEFAULT_LAYER = 0;
    public static final float DEFAULT_EDITOR_CAMERA_DRAG_DEBOUNCE = 0.032f;
    public static final float DEFAULT_EDITOR_CAMERA_LERP_TIME = 0.0f;
    public static final float DEFAULT_EDITOR_CAMERA_DRAG_SENSITIVITY = 30.0f;
    public static final float DEFAULT_EDITOR_CAMERA_SCROLL_SENSITIVITY = 0.05f;
    public static final float DEFAULT_CAMERA_ZOOM = 1f;
    public static final int DEFAULT_WINDOW_WIDTH = 1980;
    public static final int DEFAULT_WINDOW_HEIGHT = 720;
    public static final float DEFAULT_ASPECT_RATIO = 16f / 9f;
    public static final float DEFAULT_FRAME_TIME = 0.12f;
    public static final float DEFAULT_RESTITUTION = 0.5f;
    public static final float DEFAULT_FRICTION = 0.5f;
    public static final float DEFAULT_MAX_WALK_SPEED = 5f;
    public static final float DEFAULT_GROUND_ACCELERATION = 20.0f;
    public static final float DEFAULT_GROUND_DECELERATION = 20.0f;
    public static final float DEFAULT_AIR_ACCELERATION = 5f;
    public static final float DEFAULT_AIR_DECELERATION = 5f;
    public static final Vector2f DEFAULT_CAMERA_PROJECTION_SIZE = new Vector2f(16f / 3f, 9f / 3f);
    public static final float DEFAULT_FPS = 60.0f;
    public static final String DEFAULT_WINDOW_TITLE = "Just Forge 2D";
    public static final Vector4f DEFAULT_CLEAR_COLOR = new Vector4f(1.0f);
    public static final String DEFAULT_ICON_PATH = "Assets/Textures/logo.png";
    public static final boolean DEFAULT_VSYNC_ENABLE = true;
    public static final boolean DEFAULT_WINDOW_TRANSPARENCY_STATE = false;
    public static final boolean DEFAULT_WINDOW_MAXIMIZED_STATE = false;
    public static final boolean DEFAULT_WINDOW_VISIBLE_STATE = true;
    public static final boolean DEFAULT_WINDOW_DECORATION_STATE = true;
    public static final boolean DEFAULT_WINDOW_RESIZABLE_STATE = true;
    public static final boolean DEFAULT_WINDOW_FLOAT_STATUS = false;
    public static final String DEFAULT_SAVE_DIR = "/Saves";
    public static final float DEFAULT_JUMP_IMPULSE = 1f;
    public static final float DEFAULT_MAX_RUN_SPEED = 7f;
    public static final float DEFAULT_GROUND_DETECT_RAY_LENGTH = 0.05f;
    public static final float DEFAULT_COYOTE_TIME = 0.1f;
    public static final int DEFAULT_MAX_JUMPS = 1;
    public static final Keys DEFAULT_MOVE_RIGHT_KEY = Keys.D;
    public static final Keys DEFAULT_MOVE_LEFT_KEY = Keys.A;
    public static final Keys DEFAULT_RUN_KEY = Keys.CAPS_LOCK;
    public static final Keys DEFAULT_JUMP_KEY = Keys.SPACE;
    public static final ImVec4 DEFAULT_CLEAN_THEME_SECONDARY_COLOR = new ImVec4(0.129411765f, 0.1450980f, 0.16078f, 1.0f);
    public static final ImVec4 DEFAULT_CLEAN_THEME_PRIMARY_COLOR = new ImVec4(0.97647f, 0.97254902f, 0.968627541f, 1.0f);
    public static final ImVec4 DEFAULT_CLEAN_THEME_TERTIARY_COLOR = new ImVec4(0.203921569f, 0.22745f, 0.2509f, 1.0f);
    public static final ImVec4 DEFAULT_CLEAN_THEME_QUATERNARY_COLOR = new ImVec4(0.8747f, 0.892156f, 0.91760f, 1.0f);
    public static final float DEFAULT_POPUP_ROUNDING = 4f;
    public static final float DEFAULT_WINDOW_BORDER_SIZE = 0.0f;
    public static final float DEFAULT_WINDOW_ROUNDING = 0.0f;
    public static final ImVec2 DEFAULT_WINDOW_PADDING = new ImVec2(4.0f, 4.0f);
    public static final ImVec2 DEFAULT_FRAME_PADDING = new ImVec2(4.0f, 4.0f);
    public static final float DEFAULT_FRAME_ROUNDING = 4.0f;
    public static final float DEFAULT_TREE_NODE_INDENT = 16f;
    public static final float DEFAULT_TAB_ROUNDING = 4f;
    public static final float DEFAULT_TAB_BORDER = 0f;
    public static final boolean DARK_MODE_ENABLED = true;
    public static final boolean SHOW_GRID = true;
}